### ISSUE TITLE
Login problems and unable to load any data

### ISSUE THREAD

**Issue by MayaLekova** [firebase/vulcan#11]
I'm using the extension with Chromium 34.0.1847.116 (Developer Build 260972) on Ubuntu 12.04 and stumbled upon 2 problems:

1. In tab "Firebase" if I enter a secret in the "AUTHENTICATION TOKEN" field, I get `PLEASE ENTER A VALID FIREBASE URL` error
2. If I just enter the url to the Firebase app, the extension seems to log in successfully, but instead of seeing my data, the `Loading...` message stays forever

Any help would be highly appreciated!

**Comment by n370** [comment]
@hsin421 It definitely helps to remove and install again.

**Comment by joeyyang** [comment]
Hey y'all – I'm Joey, a Firebase UX engineer.

I've pushed what I believe to be a fix to this issue (and the nonfunctional Sign In button issue) in [version 1.3.1 of Vulcan](https://chrome.google.com/webstore/detail/vulcan-by-firebase/oippbnlmebalopjbkemajgfbglcjhnbl?utm_source=chrome-ntp-icon). If you download the new version (please confirm by checking the version number under [chrome://extensions/](chrome://extensions/)), your data should load. 

If this is not the case, please let me know! Hopefully this makes Vulcan usable for y'all again. Thank you all!
