### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by lima02** [firebase/vulcan#32]
I type in both URL and the Token and click Sign In. Nothing happens. No feedback. Nothing. I have tried restarting Chrome, re-enabling Vulcan and still the same. v.1.3.1.

**Comment by brendan-roche** [comment]
Yeah I'm having this issue too, cannot get past sign in, very frustrating.
Vulcan 1.3.1
Chrome 41.0.2272.118

**Comment by betzrhodes** [comment]
Having the same issue.  My database was showing data in the Vulcan console tab, and I made an edit.  The edit appeared to work in Vulcan, but did not actually update my firebase database.  I logged out, and have been unable to log back in.  After log in I get a page that says "loading..."

Chrome Version 42.0.2311.90 (64-bit)
Vulcan by Firebase version 1.3.1

**Comment by chuckh** [comment]
I having the same problem 
Version 41.0.2272.118 (64-bit) on Mac
Vulcan by Firebase version 1.3.1

**Comment by micahbolen** [comment]
Same on Linux.  What is the status on this issue?

**Comment by micahbolen** [comment]
As a stopgap measure, I rolled back to [1.3.0](https://github.com/firebase/vulcan/blob/a0977bb169c6bc6ff0968ee3cd97a7b801ec9775/chrome-extension.zip) and I'm back in business for the moment.

**Comment by danzaner** [comment]
@micahbolen Thanks! Reverting to 1.3.0 was the only thing that worked for me.

**Comment by bttf** [comment]
Same issue,
v1.3.1
Google Chrome: Version 42.0.2311.135 m
Windows 8.1

**Comment by joeyyang** [comment]
Hi everyone — Thank you all for reporting this. I just pushed a fix to version 1.3.2, available in the [Chrome App Store](https://chrome.google.com/webstore/detail/vulcan-by-firebase/oippbnlmebalopjbkemajgfbglcjhnbl). Please try upgrading and let me know if you're still having this issue!
