### ISSUE TITLE
Extension Does Not Load

### ISSUE THREAD

**Issue by jasoncavett** [firebase/vulcan#34]
Issue: When I open Vulcan and add my URL to my Firebase instance (no authentication), it just sits with a "Loading..." message in the extension. Nothing else happens.

Browser / Version: Chrome 43.0.2357.18 beta (64-bit)
OS: OSX (Yosemite)
Vulcan Version: 1.3.1

**Comment by bakkerjean** [comment]
Hi Jason, I had the same issue. For me it was resolved after I removed and re-added the extension in chrome.

**Comment by jasoncavett** [comment]
Hi @bakkerjean. I just tested it out, and removing and re-adding half fixed the problem. I am now able to connect to my Firebase instance again, but when I try to add anything (a Child, for example) to my instance through the interface, nothing gets added. I can file a separate bug if appropriate.

**Comment by joeyyang** [comment]
Hi @jasoncavett and @bakkerjean  — Thank you both for reporting this. I just pushed a fix to version 1.3.2, available in the [Chrome App Store](https://chrome.google.com/webstore/detail/vulcan-by-firebase/oippbnlmebalopjbkemajgfbglcjhnbl). Please try upgrading and let me know if you're still having this issue!

**Comment by jasoncavett** [comment]
Hi @joeyyang - Everything appears to be working well. When I used @bakkerjean's method of reinstalling, it fixed the problem as well, but after a bit, the problem happened again. I'll let you know if that happens. Otherwise, the fix is working. Thank you much!

**Comment by joeyyang** [comment]
@jasoncavett great to hear; please send along any other issues you encounter!
