### ISSUE TITLE
Security Vulnerability

### ISSUE THREAD

**Issue by cbanowsky** [firebase/vulcan#36]
Vulcan allows an unauthenticated user to access firebase url.  I can edit the tables in a url that I am not signed into.  I would check it out so people don't start changing my database.

**Comment by alexwolfe** [comment]
Firebase urls without rules can be edited/accessed. This is simply a feature of Firebase. In order to secure your data I recommend reading the [Security Quickstart](https://www.firebase.com/docs/security/quickstart.html)

**Comment by katowulf** [comment]
Be happy to have a look at this. However, since security is controlled by declarative rules in Firebase, and not by Vulcan, this would at first glance seem utterly impossible. Given that initial assessment, I think we'd need to see an initial proof that demonstrates the issue.

**Comment by cbanowsky** [comment]
Ok thank you for getting back to me on this.
