### ISSUE TITLE
Can't login; no response in UI or console

### ISSUE THREAD

**Issue by danzaner** [firebase/vulcan#38]
I've already downgraded Vulcan to 1.3.0 because of this unresolved login issue that's been open since April 6th: https://github.com/firebase/vulcan/issues/32

Now 1.3.0 does not log in either. There's no response from Vulcan in the UI or the console. There's been no response from Firebase, either, I might add.

**Comment by alexwolfe** [comment]
@joeyyang you still looking at this?

**Comment by joeyyang** [comment]
Yup, got a branch up for review here:
https://github.com/firebase/vulcan/pull/35

Pretty slammed at the moment, but will come back to this soon!

**Comment by estbyright** [comment]
I have the same issue. v 1.3.1.

**Comment by joeyyang** [comment]
Hi @danzaner and @estbyright — Thank you both for reporting this. I just pushed a fix to version 1.3.2, available in the [Chrome App Store](https://chrome.google.com/webstore/detail/vulcan-by-firebase/oippbnlmebalopjbkemajgfbglcjhnbl). Please try upgrading and let me know if you're still having this issue!

**Comment by danzaner** [comment]
@joeyyang I was able to log in using v1.3.2. Thanks for the fix.
