### ISSUE TITLE
hangs on signing in

### ISSUE THREAD

**Issue by malikasinger1** [firebase/vulcan#43]
![fgwreg](https://cloud.githubusercontent.com/assets/14273842/10017907/c47e5866-60de-11e5-9ab6-2c9f0c2cd8a0.JPG)

**Comment by kpgarrod** [comment]
+1

**Comment by malikasinger1** [comment]
what do you mean by  "+1"

**Comment by kpgarrod** [comment]
@malikasinger: I am having the same issue and unable to use Vulcan at all. Do you have a workaround?

**Comment by vzhen** [comment]
same here

**Comment by joeyyang** [comment]
Hi all — this should be fixed in `1.5.0`, which is rolling out to the Chrome Store right now. Thanks for reporting!
