### ISSUE TITLE
Vulcan not ready for Google Login

### ISSUE THREAD

**Issue by eillarra** [firebase/vulcan#44]
If you update your login credentials to use Google Login, you can't login on Vulcan anymore.

More info: https://www.firebase.com/blog/2015-10-13-google-login-and-firebase-cli-2.html

**Comment by cubissimo** [comment]
+1

**Comment by reganstarr** [comment]
+1

**Comment by jarmop** [comment]
+1

**Comment by michaeldoye** [comment]
+1

**Comment by Temmermans** [comment]
+1

**Comment by numerized** [comment]
+1

**Comment by appie18** [comment]
Please fix this, its very frustrating.

**Comment by ce-acatl** [comment]
+1

**Comment by jonstodle** [comment]
+1

**Comment by osvaldoros** [comment]
+1

**Comment by jedwood** [comment]
+1 wish I would have realized this before I switched to Google Login. :/

**Comment by octopitus** [comment]
+1

**Comment by sarah-maris** [comment]
+1

**Comment by styxali** [comment]
+1

**Comment by joeyyang** [comment]
Hi all — this is fixed in `1.5.0`, which should be rolling out to the Chrome Store right now. Thanks for reporting everyone!
